api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    swagger:
        versions: [3]
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    collection:
        pagination:
            # The default name of the parameter handling the page number.
            page_parameter_name: 'page'
            # The name of the query parameter to set the number of items per page.
            items_per_page_parameter_name: 'count'
